-- 步骤1：创建XXL_JOB模式（达梦原生语法）
CREATE SCHEMA XXL_JOB;

-- 步骤2：切换到XXL_JOB模式
SET SCHEMA XXL_JOB;

-- —————————————————————— 步骤3：创建所有表（核心修复TITLE列长度） ——————————————————
-- 执行器分组表（修复TITLE列：VARCHAR(12) → VARCHAR(32)）
CREATE TABLE XXL_JOB_GROUP
(
    ID           INT           NOT NULL IDENTITY(1,1),
    APP_NAME     VARCHAR(64)   NOT NULL,
    TITLE        VARCHAR(32)   NOT NULL,  -- 核心修改：从12改为32，足够容纳业务名称
    ADDRESS_TYPE TINYINT       NOT NULL DEFAULT 0,
    ADDRESS_LIST TEXT,
    UPDATE_TIME  DATETIME      DEFAULT NULL,
    PRIMARY KEY (ID)
) STORAGE(ON MAIN);

-- 执行器注册表
CREATE TABLE XXL_JOB_REGISTRY
(
    ID             INT           NOT NULL IDENTITY(1,1),
    REGISTRY_GROUP VARCHAR(50)   NOT NULL,
    REGISTRY_KEY   VARCHAR(255)  NOT NULL,
    REGISTRY_VALUE VARCHAR(255)  NOT NULL,
    UPDATE_TIME    DATETIME      DEFAULT NULL,
    PRIMARY KEY (ID),
    UNIQUE (REGISTRY_GROUP, REGISTRY_KEY, REGISTRY_VALUE)
) STORAGE(ON MAIN);

-- 任务信息表
CREATE TABLE XXL_JOB_INFO
(
    ID                        INT           NOT NULL IDENTITY(1,1),
    JOB_GROUP                 INT           NOT NULL,
    JOB_DESC                  VARCHAR(255)  NOT NULL,
    ADD_TIME                  DATETIME      DEFAULT NULL,
    UPDATE_TIME               DATETIME      DEFAULT NULL,
    AUTHOR                    VARCHAR(64)   DEFAULT NULL,
    ALARM_EMAIL               VARCHAR(255)  DEFAULT NULL,
    SCHEDULE_TYPE             VARCHAR(50)   NOT NULL DEFAULT 'NONE',
    SCHEDULE_CONF             VARCHAR(128)  DEFAULT NULL,
    MISFIRE_STRATEGY          VARCHAR(50)   NOT NULL DEFAULT 'DO_NOTHING',
    EXECUTOR_ROUTE_STRATEGY   VARCHAR(50)   DEFAULT NULL,
    EXECUTOR_HANDLER          VARCHAR(255)  DEFAULT NULL,
    EXECUTOR_PARAM            VARCHAR(512)  DEFAULT NULL,
    EXECUTOR_BLOCK_STRATEGY   VARCHAR(50)   DEFAULT NULL,
    EXECUTOR_TIMEOUT          INT           NOT NULL DEFAULT 0,
    EXECUTOR_FAIL_RETRY_COUNT INT           NOT NULL DEFAULT 0,
    GLUE_TYPE                 VARCHAR(50)   NOT NULL,
    GLUE_SOURCE               CLOB,
    GLUE_REMARK               VARCHAR(128)  DEFAULT NULL,
    GLUE_UPDATETIME           DATETIME      DEFAULT NULL,
    CHILD_JOBID               VARCHAR(255)  DEFAULT NULL,
    TRIGGER_STATUS            TINYINT       NOT NULL DEFAULT 0,
    TRIGGER_LAST_TIME         BIGINT        NOT NULL DEFAULT 0,
    TRIGGER_NEXT_TIME         BIGINT        NOT NULL DEFAULT 0,
    PRIMARY KEY (ID)
) STORAGE(ON MAIN);

-- 任务GLUE日志表
CREATE TABLE XXL_JOB_LOGGLUE
(
    ID          INT           NOT NULL IDENTITY(1,1),
    JOB_ID      INT           NOT NULL,
    GLUE_TYPE   VARCHAR(50)   DEFAULT NULL,
    GLUE_SOURCE CLOB,
    GLUE_REMARK VARCHAR(128)  NOT NULL,
    ADD_TIME    DATETIME      DEFAULT NULL,
    UPDATE_TIME DATETIME      DEFAULT NULL,
    PRIMARY KEY (ID)
) STORAGE(ON MAIN);

-- 任务执行日志表
CREATE TABLE XXL_JOB_LOG
(
    ID                        BIGINT        NOT NULL IDENTITY(1,1),
    JOB_GROUP                 INT           NOT NULL,
    JOB_ID                    INT           NOT NULL,
    EXECUTOR_ADDRESS          VARCHAR(255)  DEFAULT NULL,
    EXECUTOR_HANDLER          VARCHAR(255)  DEFAULT NULL,
    EXECUTOR_PARAM            VARCHAR(512)  DEFAULT NULL,
    EXECUTOR_SHARDING_PARAM   VARCHAR(20)   DEFAULT NULL,
    EXECUTOR_FAIL_RETRY_COUNT INT           NOT NULL DEFAULT 0,
    TRIGGER_TIME              DATETIME      DEFAULT NULL,
    TRIGGER_CODE              INT           NOT NULL,
    TRIGGER_MSG               CLOB,
    HANDLE_TIME               DATETIME      DEFAULT NULL,
    HANDLE_CODE               INT           NOT NULL,
    HANDLE_MSG                CLOB,
    ALARM_STATUS              TINYINT       NOT NULL DEFAULT 0,
    PRIMARY KEY (ID)
) STORAGE(ON MAIN);

-- 任务执行日志报表
CREATE TABLE XXL_JOB_LOG_REPORT
(
    ID            INT           NOT NULL IDENTITY(1,1),
    TRIGGER_DAY   DATETIME      DEFAULT NULL,
    RUNNING_COUNT INT           NOT NULL DEFAULT 0,
    SUC_COUNT     INT           NOT NULL DEFAULT 0,
    FAIL_COUNT    INT           NOT NULL DEFAULT 0,
    UPDATE_TIME   DATETIME      DEFAULT NULL,
    PRIMARY KEY (ID),
    UNIQUE (TRIGGER_DAY)
) STORAGE(ON MAIN);

-- 任务锁表
CREATE TABLE XXL_JOB_LOCK
(
    LOCK_NAME VARCHAR(50)   NOT NULL,
    PRIMARY KEY (LOCK_NAME)
) STORAGE(ON MAIN);

-- 用户表
CREATE TABLE XXL_JOB_USER
(
    ID         INT           NOT NULL IDENTITY(1,1),
    USERNAME   VARCHAR(50)   NOT NULL,
    PASSWORD   VARCHAR(100)  NOT NULL,
    TOKEN      VARCHAR(100)  DEFAULT NULL,
    ROLE       TINYINT       NOT NULL,
    PERMISSION VARCHAR(255)  DEFAULT NULL,
    PRIMARY KEY (ID),
    UNIQUE (USERNAME)
) STORAGE(ON MAIN);

-- —————————————————————— 步骤4：创建普通索引 ——————————————————
CREATE INDEX IDX_XXL_JOB_LOG_TRIGGER_TIME ON XXL_JOB_LOG(TRIGGER_TIME);
CREATE INDEX IDX_XXL_JOB_LOG_HANDLE_CODE ON XXL_JOB_LOG(HANDLE_CODE);
CREATE INDEX IDX_XXL_JOB_LOG_JOBID_JOBGROUP ON XXL_JOB_LOG(JOB_ID,JOB_GROUP);
CREATE INDEX IDX_XXL_JOB_LOG_JOB_ID ON XXL_JOB_LOG(JOB_ID);

-- —————————————————————— 步骤5：添加所有表/列备注 ——————————————————
-- XXL_JOB_GROUP备注
COMMENT ON TABLE XXL_JOB_GROUP IS '执行器分组表';
COMMENT ON COLUMN XXL_JOB_GROUP.ID IS '主键ID';
COMMENT ON COLUMN XXL_JOB_GROUP.APP_NAME IS '执行器AppName';
COMMENT ON COLUMN XXL_JOB_GROUP.TITLE IS '执行器名称';
COMMENT ON COLUMN XXL_JOB_GROUP.ADDRESS_TYPE IS '执行器地址类型：0=自动注册、1=手动录入';
COMMENT ON COLUMN XXL_JOB_GROUP.ADDRESS_LIST IS '执行器地址列表，多地址逗号分隔';
COMMENT ON COLUMN XXL_JOB_GROUP.UPDATE_TIME IS '更新时间';

-- XXL_JOB_REGISTRY备注
COMMENT ON TABLE XXL_JOB_REGISTRY IS '执行器注册表';
COMMENT ON COLUMN XXL_JOB_REGISTRY.ID IS '主键ID';
COMMENT ON COLUMN XXL_JOB_REGISTRY.REGISTRY_GROUP IS '注册分组';
COMMENT ON COLUMN XXL_JOB_REGISTRY.REGISTRY_KEY IS '注册键';
COMMENT ON COLUMN XXL_JOB_REGISTRY.REGISTRY_VALUE IS '注册值';
COMMENT ON COLUMN XXL_JOB_REGISTRY.UPDATE_TIME IS '更新时间';

-- XXL_JOB_INFO备注
COMMENT ON TABLE XXL_JOB_INFO IS '任务信息表';
COMMENT ON COLUMN XXL_JOB_INFO.ID IS '主键ID';
COMMENT ON COLUMN XXL_JOB_INFO.JOB_GROUP IS '执行器主键ID';
COMMENT ON COLUMN XXL_JOB_INFO.JOB_DESC IS '任务描述';
COMMENT ON COLUMN XXL_JOB_INFO.ADD_TIME IS '添加时间';
COMMENT ON COLUMN XXL_JOB_INFO.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN XXL_JOB_INFO.AUTHOR IS '作者';
COMMENT ON COLUMN XXL_JOB_INFO.ALARM_EMAIL IS '报警邮件';
COMMENT ON COLUMN XXL_JOB_INFO.SCHEDULE_TYPE IS '调度类型';
COMMENT ON COLUMN XXL_JOB_INFO.SCHEDULE_CONF IS '调度配置，值含义取决于调度类型';
COMMENT ON COLUMN XXL_JOB_INFO.MISFIRE_STRATEGY IS '调度过期策略';
COMMENT ON COLUMN XXL_JOB_INFO.EXECUTOR_ROUTE_STRATEGY IS '执行器路由策略';
COMMENT ON COLUMN XXL_JOB_INFO.EXECUTOR_HANDLER IS '执行器任务handler';
COMMENT ON COLUMN XXL_JOB_INFO.EXECUTOR_PARAM IS '执行器任务参数';
COMMENT ON COLUMN XXL_JOB_INFO.EXECUTOR_BLOCK_STRATEGY IS '阻塞处理策略';
COMMENT ON COLUMN XXL_JOB_INFO.EXECUTOR_TIMEOUT IS '任务执行超时时间，单位秒';
COMMENT ON COLUMN XXL_JOB_INFO.EXECUTOR_FAIL_RETRY_COUNT IS '失败重试次数';
COMMENT ON COLUMN XXL_JOB_INFO.GLUE_TYPE IS 'GLUE类型';
COMMENT ON COLUMN XXL_JOB_INFO.GLUE_SOURCE IS 'GLUE源代码';
COMMENT ON COLUMN XXL_JOB_INFO.GLUE_REMARK IS 'GLUE备注';
COMMENT ON COLUMN XXL_JOB_INFO.GLUE_UPDATETIME IS 'GLUE更新时间';
COMMENT ON COLUMN XXL_JOB_INFO.CHILD_JOBID IS '子任务ID，多个逗号分隔';
COMMENT ON COLUMN XXL_JOB_INFO.TRIGGER_STATUS IS '调度状态：0-停止，1-运行';
COMMENT ON COLUMN XXL_JOB_INFO.TRIGGER_LAST_TIME IS '上次调度时间';
COMMENT ON COLUMN XXL_JOB_INFO.TRIGGER_NEXT_TIME IS '下次调度时间';

-- XXL_JOB_LOGGLUE备注
COMMENT ON TABLE XXL_JOB_LOGGLUE IS '任务GLUE日志表';
COMMENT ON COLUMN XXL_JOB_LOGGLUE.ID IS '主键ID';
COMMENT ON COLUMN XXL_JOB_LOGGLUE.JOB_ID IS '任务，主键ID';
COMMENT ON COLUMN XXL_JOB_LOGGLUE.GLUE_TYPE IS 'GLUE类型';
COMMENT ON COLUMN XXL_JOB_LOGGLUE.GLUE_SOURCE IS 'GLUE源代码';
COMMENT ON COLUMN XXL_JOB_LOGGLUE.GLUE_REMARK IS 'GLUE备注';
COMMENT ON COLUMN XXL_JOB_LOGGLUE.ADD_TIME IS '添加时间';
COMMENT ON COLUMN XXL_JOB_LOGGLUE.UPDATE_TIME IS '更新时间';

-- XXL_JOB_LOG备注
COMMENT ON TABLE XXL_JOB_LOG IS '任务执行日志表';
COMMENT ON COLUMN XXL_JOB_LOG.ID IS '主键ID';
COMMENT ON COLUMN XXL_JOB_LOG.JOB_GROUP IS '执行器主键ID';
COMMENT ON COLUMN XXL_JOB_LOG.JOB_ID IS '任务，主键ID';
COMMENT ON COLUMN XXL_JOB_LOG.EXECUTOR_ADDRESS IS '执行器地址，本次执行的地址';
COMMENT ON COLUMN XXL_JOB_LOG.EXECUTOR_HANDLER IS '执行器任务handler';
COMMENT ON COLUMN XXL_JOB_LOG.EXECUTOR_PARAM IS '执行器任务参数';
COMMENT ON COLUMN XXL_JOB_LOG.EXECUTOR_SHARDING_PARAM IS '执行器任务分片参数，格式如 1/2';
COMMENT ON COLUMN XXL_JOB_LOG.EXECUTOR_FAIL_RETRY_COUNT IS '失败重试次数';
COMMENT ON COLUMN XXL_JOB_LOG.TRIGGER_TIME IS '调度-时间';
COMMENT ON COLUMN XXL_JOB_LOG.TRIGGER_CODE IS '调度-结果';
COMMENT ON COLUMN XXL_JOB_LOG.TRIGGER_MSG IS '调度-日志';
COMMENT ON COLUMN XXL_JOB_LOG.HANDLE_TIME IS '执行-时间';
COMMENT ON COLUMN XXL_JOB_LOG.HANDLE_CODE IS '执行-状态';
COMMENT ON COLUMN XXL_JOB_LOG.HANDLE_MSG IS '执行-日志';
COMMENT ON COLUMN XXL_JOB_LOG.ALARM_STATUS IS '告警状态：0-默认、1-无需告警、2-告警成功、3-告警失败';

-- XXL_JOB_LOG_REPORT备注
COMMENT ON TABLE XXL_JOB_LOG_REPORT IS '任务执行日志报表';
COMMENT ON COLUMN XXL_JOB_LOG_REPORT.ID IS '主键ID';
COMMENT ON COLUMN XXL_JOB_LOG_REPORT.TRIGGER_DAY IS '调度-时间';
COMMENT ON COLUMN XXL_JOB_LOG_REPORT.RUNNING_COUNT IS '运行中-日志数量';
COMMENT ON COLUMN XXL_JOB_LOG_REPORT.SUC_COUNT IS '执行成功-日志数量';
COMMENT ON COLUMN XXL_JOB_LOG_REPORT.FAIL_COUNT IS '执行失败-日志数量';
COMMENT ON COLUMN XXL_JOB_LOG_REPORT.UPDATE_TIME IS '更新时间';

-- XXL_JOB_LOCK备注
COMMENT ON TABLE XXL_JOB_LOCK IS '任务锁表';
COMMENT ON COLUMN XXL_JOB_LOCK.LOCK_NAME IS '锁名称';

-- XXL_JOB_USER备注
COMMENT ON TABLE XXL_JOB_USER IS '用户表';
COMMENT ON COLUMN XXL_JOB_USER.ID IS '主键ID';
COMMENT ON COLUMN XXL_JOB_USER.USERNAME IS '账号';
COMMENT ON COLUMN XXL_JOB_USER.PASSWORD IS '密码加密信息';
COMMENT ON COLUMN XXL_JOB_USER.TOKEN IS '登录token';
COMMENT ON COLUMN XXL_JOB_USER.ROLE IS '角色：0-普通用户、1-管理员';
COMMENT ON COLUMN XXL_JOB_USER.PERMISSION IS '权限：执行器ID列表，多个逗号分割';

-- —————————————————————— 步骤6：插入默认数据（适配自增列+列长度） ——————————————————
-- 1. 插入XXL_JOB_GROUP（先开启自增赋值，数据长度适配VARCHAR(32)）
SET IDENTITY_INSERT XXL_JOB_GROUP ON;
INSERT INTO XXL_JOB_GROUP(ID, APP_NAME, TITLE, ADDRESS_TYPE, ADDRESS_LIST, UPDATE_TIME)
VALUES (1, 'xxl-job-executor-sample', '通用执行器Sample', 0, NULL, NOW()),
       (2, 'xxl-job-executor-sample-ai', 'AI执行器Sample', 0, NULL, NOW());
SET IDENTITY_INSERT XXL_JOB_GROUP OFF;

-- 2. 插入XXL_JOB_INFO（先开启自增赋值）
SET IDENTITY_INSERT XXL_JOB_INFO ON;
INSERT INTO XXL_JOB_INFO(ID, JOB_GROUP, JOB_DESC, ADD_TIME, UPDATE_TIME, AUTHOR, ALARM_EMAIL,
                         SCHEDULE_TYPE, SCHEDULE_CONF, MISFIRE_STRATEGY, EXECUTOR_ROUTE_STRATEGY,
                         EXECUTOR_HANDLER, EXECUTOR_PARAM, EXECUTOR_BLOCK_STRATEGY, EXECUTOR_TIMEOUT,
                         EXECUTOR_FAIL_RETRY_COUNT, GLUE_TYPE, GLUE_SOURCE, GLUE_REMARK, GLUE_UPDATETIME,
                         CHILD_JOBID)
VALUES (1, 1, '示例任务01', NOW(), NOW(), 'XXL', '', 'CRON', '0 0 0 * * ? *',
        'DO_NOTHING', 'FIRST', 'demoJobHandler', '', 'SERIAL_EXECUTION', 0, 0, 'BEAN', '', 'GLUE代码初始化',
        NOW(), ''),
       (2, 2, 'Ollama示例任务01', NOW(), NOW(), 'XXL', '', 'NONE', '',
        'DO_NOTHING', 'FIRST', 'ollamaJobHandler', '{
    "input": "慢SQL问题分析思路",
    "prompt": "你是一个研发工程师，擅长解决技术类问题。",
    "model": "qwen3:0.6b"
}', 'SERIAL_EXECUTION', 0, 0, 'BEAN', '', 'GLUE代码初始化',
        NOW(), ''),
       (3, 2, 'Dify示例任务', NOW(), NOW(), 'XXL', '', 'NONE', '',
        'DO_NOTHING', 'FIRST', 'difyWorkflowJobHandler', '{
    "inputs":{
        "input":"查询班级各学科前三名"
    },
    "user": "xxl-job",
    "baseUrl": "http://localhost/v1",
    "apiKey": "app-OUVgNUOQRIMokfmuJvBJoUTN"
}', 'SERIAL_EXECUTION', 0, 0, 'BEAN', '', 'GLUE代码初始化',
        NOW(), '');
SET IDENTITY_INSERT XXL_JOB_INFO OFF;

-- 3. 插入XXL_JOB_USER（先开启自增赋值）
SET IDENTITY_INSERT XXL_JOB_USER ON;
INSERT INTO XXL_JOB_USER(ID, USERNAME, PASSWORD, ROLE, PERMISSION)
VALUES (1, 'admin', '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92', 1, NULL);
SET IDENTITY_INSERT XXL_JOB_USER OFF;

-- 4. 插入XXL_JOB_LOCK（无自增列，直接插入）
INSERT INTO XXL_JOB_LOCK (LOCK_NAME)
VALUES ('schedule_lock');

-- 提交事务
COMMIT;